### ISSUE TITLE
Trained model file of TREC CAR

### ISSUE THREAD

**Issue by ChrisRBXiong** [nyu-dl/dl4ir-doc2query#1]
Hi, I noticed that the result of trec car 2017 is also presented on your paper. Would you mind release the trained model file of the Trec CAR, as you already done of the MS MARCO? Thanks a lot!

**Comment by rodrigonogueira4** [comment]
Sure, here you go:
https://drive.google.com/open?id=16KT1Lxax_gOewSAz8FqQlwcdpspkmwQ3

**Comment by ChrisRBXiong** [comment]
Thanks very much!

Rodrigo Frassetto Nogueira <notifications@github.com> 于2019年6月16日周日
上午7:56写道：
