### ISSUE TITLE
A simple question about the paper：What is the training data for doc2query transformer? Thank you very much!

### ISSUE THREAD

**Issue by guotong1988** [nyu-dl/dl4ir-doc2query#2]
Sorry I'm new to this paper.
What is the training data for doc2query transformer?
I guess the training data is the origin doc and its corresponding query pair.
Thank you!! 
@rodrigonogueira4

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/60557198-2477a280-9d77-11e9-93de-522edd9b6dc2.png)

**Comment by rodrigonogueira4** [comment]
The input to the transformer is a relevant document and the desired output is a query. For MS MARCO, we have 500k of these query-relevant doc pairs.
Please let me know if that answers your question.

**Comment by guotong1988** [comment]
Thank you. I understand it!
