### ISSUE TITLE
Big question, BERT ranking need triple to train, but...

### ISSUE THREAD

**Issue by guotong1988** [nyu-dl/dl4ir-doc2query#7]
https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz
The data above do not contains the negative doc.

@rodrigonogueira4 Thank you!!!

The data is from readme here:  https://github.com/nyu-dl/dl4ir-doc2query#ms-marco
![image](https://user-images.githubusercontent.com/4702353/62607788-37aafe80-b931-11e9-8b4d-cb389a514dda.png)

**Comment by rodrigonogueira4** [comment]
To train the se2seq model you only need pairs of queries and relevant documents, hence you don't need negatives.

Please post doc2query-related questions in that repository:
https://github.com/nyu-dl/dl4ir-doc2query

**Comment by guotong1988** [comment]
But BERT ranking step need the negative doc.

**Comment by rodrigonogueira4** [comment]
Please note that this repository only contains the code to train doc2query (seq2seq) model. If you want to train BERT re-ranker, please follow the steps in https://github.com/nyu-dl/dl4marco-bert.

Also, please note that training BERT re-ranker on the expanded documents did not give better results than training on the non-expanded (original) documents. I.e., you can use the trained model from https://github.com/nyu-dl/dl4marco-bert to re-rank the expanded documents.

**Comment by guotong1988** [comment]
Thank you.
